version: '3'
services:
  bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - MASTER_KEY=${MASTER_KEY}
      - TBOT_ALLOWED_USER_IDS=${TBOT_ALLOWED_USER_IDS}
    volumes:
      - ./data:/data
