services:
  bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN:--ABSENT--}
      - MASTER_KEY=${MASTER_KEY:--ABSENT--}
      - TBOT_ALLOWED_USER_IDS=${TBOT_ALLOWED_USER_IDS:--ABSENT--}
    volumes:
      - ${TBOT_DATA_PATH}:/data
