services:
  bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN:--ABSENT--}
      - MASTER_KEY=${MASTER_KEY:--ABSENT--}
      - TBOT_ALLOWED_USER_IDS=${TBOT_ALLOWED_USER_IDS:--ABSENT--}
    volumes:
      - ${TBOT_DATA_PATH}:/data
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-north-1
        awslogs-group: /ec2/ai-telegram-link
        awslogs-stream: bot
        awslogs-create-group: "true"
