services:
  bot:
    build: .
    environment:
      - TBOT_TELEGRAM_KEY=${TBOT_TELEGRAM_KEY:--ABSENT--}
      - TBOT_MASTER_KEY=${TBOT_MASTER_KEY:--ABSENT--}
      - TBOT_CHATGPT_KEY=${TBOT_CHATGPT_KEY:--ABSENT--}
      - TBOT_ALLOWED_USER_IDS=${TBOT_ALLOWED_USER_IDS:--ABSENT--}
      - TBOT_HISTORY_LIMIT=${TBOT_HISTORY_LIMIT:--ABSENT--}
    volumes:
      - ${TBOT_DATA_PATH}:/data
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-north-1
        awslogs-group: /ec2/ai-telegram-link
        awslogs-stream: bot
        awslogs-create-group: "true"
